[package]
name = "nanobot"
version = "0.1.0"
authors = ["qwerty <qwerty.knagira@gmail.com>"]

[dependencies]
getopts = "0.2"
rand = "0.5"

[lib]
name = "nanobot_lib"
path = "src/lib.rs"

[[bin]]
name = "score"
path = "src/bin/score.rs"

[[bin]]
name = "nanobot"
path = "src/main.rs"
